### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by emilydaemon** [irrnalinux/irrnalinux.github.io#2]
This project is violating the CC-BY-SA license of the IrrNa Linux logo. As of commit 8733ef858941f6a01e89756ad7ade54a1026e3cd, the project has violated the license. The CC-BY-SA license requires any project using creative works licensed under it to use the same license and give attribution (credit) to the original work and it's author. I hope we can resolve this without having to move on to harsher methods such as a DMCA takedown.
If this issue goes unnoticed for 7 days, don't be surprised if your repository goes down all of a sudden.

**Comment by irrnalinux** [comment]
YOU'VE MADE ME MAD. alright?
Now i will add your credit back. Any consequenses of making me mad with your stupid friends, i am sorry but it's going to be your problem.

**Comment by irrnalinux** [comment]
view commit https://github.com/irrnalinux/irrnalinux.github.io/commit/6abf32f0c6d78aa165043898fe97cee2a054bb10
